### ISSUE TITLE
Additional formal delimiter to parse artist seperated by comma 

### ISSUE THREAD

**Issue by alim4r** [krateng/maloja#120]
Multiple artist that are seperated by `,` won't be parsed correctly.

### Example
```
1650364543|{"track_artists": ["K/DA, Madison Beer & (G)I-DLE feat. Jaira Burns & League of Legends"], "track_title": "POP/STARS", "scrobble_time": 1650364543}|client:PC||2315|{}
```
will be parsed as:
```python
cla.fullclean("K/DA, Madison Beer & (G)I-DLE feat. Jaira Burns & League of Legends", "POP/STARS")
(['(G)I-DLE', 'DA, Madison Beer', 'Jaira Burns', 'K', 'League of Legends'], 'POP/STARS')
```

### Test
It works after adding `,` to delimiters_formal with the environment variable  `MALOJA_DELIMITERS_FORMAL=[";","/","|","␝","␞","␟",","]` 
```python
(['(G)I-DLE', 'Jaira Burns', 'K/DA', 'League of Legends', 'Madison Beer'], 'POP/STARS')
```

### Fix old parsed scrobbles?
Is it possible to reparse the old scrobbles?

**Comment by krateng** [comment]
Ah, a fellow K/DA connoisseur :D

I decided to leave out the Comma as delimiter as it's part of some artist names. I'm planning to bring the functionality to fix old scrobbles back, but right now it can only be done via direct database access (make sure to backup the file):

In case you don't have any other scrobbles by either Madison Beer or K/DA in your database, it's very simple
* In the `artists` table, rename `K` to `K/DA`
* In the `artists` table, rename `DA, Madison Beer` to `Madison Beer`

Otherwise, the comprehensive fix would be:
* Note the IDs of `Madison Beer` and `K/DA` in the `artists` table or add them if they don't exist
* Note the IDs of `K` and `DA, Madison Beer` in the `artists` table
* In the `trackartists` table, there will be two entries with `track_id` `2315` and `artist_id` one of the two from Step 2 - replace the `artist_id` of each with one of the two from Step 1.

Sorry for the inconvenience! I hope to reimplement this soon.

**Comment by alim4r** [comment]
Ok thanks, I didn't think of artists that use commas 🤔.

I used the second option and just changed the `track_id` for the scrobble.

Where `2775` is the `track_id` of a scrobble of the same song but with fixed delimiter/rules and `2315` the `track_id` of the track with wrong infos.
```sql
UPDATE scrobbles SET track_id = 2775 WHERE track_id = 2315;
```

**Comment by krateng** [comment]
That's... much simpler. Don't know why I didn't even think of that :D
