### ISSUE TITLE
Use local timezone by default

### ISSUE THREAD

**Issue by SurmanPP** [krateng/maloja#198]
datatime.now() gives the local time by default. Instead of no timetzone 0 is used meaning that I get UTC if the option is unset instead of the localtime which makes more sense. I would even go as far as to say this option is useless most(if not everyone) want to use local time instead of UTC.

If one really wanted to change the timezone they could use the TZ environment variable.

**Comment by krateng** [comment]
There's no right and wrong about defaults, but my philosophy on the matter is that servers and their processes should [always use UTC](http://yellerapp.com/posts/2015-01-12-the-worst-server-setup-you-can-make.html) and never behave differently based on locale (especially considering local timezone could literally change due to daylight savings) - all user-facing output can be formatted by explicit setting (or should, as soon as #200 is fixed :D).

Same for #199
