### ISSUE TITLE
When some tracks of an album has a Feat, it counts as a separate album

### ISSUE THREAD

**Issue by Fratt** [krateng/maloja#294]
![image](https://github.com/krateng/maloja/assets/10696066/6bbb94bb-207e-42a6-8c67-e93d3bc2f975)
![image](https://github.com/krateng/maloja/assets/10696066/8ed5ba99-dfb9-434f-b23a-a24d24fcb6ea)
![image](https://github.com/krateng/maloja/assets/10696066/8bb772ec-f11d-4526-bd09-59076aef0243)
![image](https://github.com/krateng/maloja/assets/10696066/c2b03bdc-715d-4311-8c6b-4cc17915bf9b)

How do I prevent that from happening ? The tracks Feat Roy Khan should show up in the "Serenity" album too.

**Comment by krateng** [comment]
The scrobble payload has to send information about the album artist, otherwise Maloja will just assume it's the same as the track artists. To fix this, navigate to the wrong album in the web interface with admin mode enabled, click the little 'mark for merge' icon, then go to the correct album and click 'merge'.

**Comment by Fratt** [comment]
Great, thanks, it worked!
Next time I will scrobble one of those songs, they will still end up on the right album?
Thx

**Comment by krateng** [comment]
Yes, once an album is applied to a track it's not changed by default.
