### ISSUE TITLE
add wand to requirements.txt

### ISSUE THREAD

**Issue by CultofRobots** [krateng/maloja#3]
Wand is not in requirements.txt

output from maloja start:
> Server is not running
> The following python modules are highly recommended, some features will not work without them:
> 	wand
> You can install them with pip install -r requirements.txt or Maloja can try to install them automatically. For this, you need to run this script as a root user.

fixed by adding `wand>=0.5.4` to requirements.txt and rerunning pip3 install

**Comment by krateng** [comment]
Ah, that's an oversight in the install script. Wand is technically not a requirement as the server runs without it, it's only needed for some optional bandwidth improvements. Since there is no real downside to just installing it, I'll just add it to the requirements.txt as you suggested and possibly improve the install script a bit in the future.
