### ISSUE TITLE
Wrong artist picture

### ISSUE THREAD

**Issue by bznein** [krateng/maloja#365]
Hello,

I've just installed maloja on my home server. After playing a few songs I opened it to look at it, and noticed that my #1 artist has a wrong picture.

![image](https://github.com/krateng/maloja/assets/11992814/1d800924-9326-4145-acd0-e12d8db40bf1)

The artist is the canadian band Rush ([LastFM](https://www.last.fm/music/Rush), [Spotify](https://open.spotify.com/artist/2Hkut4rAAyrQxRdof7FVJq)), but the picture is of actor/singer [Troye Sivan](https://en.wikipedia.org/wiki/Troye_Sivan).

Any idea what might cause this and how to change it?

Thank you!

**Comment by gBasil** [comment]
Maloja uses the MusicBrainz API (or some similar API) to look up images. However, it can sometimes fail to get the proper image, since it just uses the top search result it recieves, and sometimes there just isn't an image for a certain artist/song. If you enable admin mode, you can drag and drop an image file from your computer (note: it must be a downloaded image) onto the image to update it.

**Comment by bznein** [comment]
Ah thank you! Is this drag and drop feature documented anywhere? I didn't see it in the docs
