### ISSUE TITLE
Thanks for sharing this with me on Reddit but

### ISSUE THREAD

**Issue by Behinder** [krateng/maloja#48]
However I would like to have possibility to turn off "this week", e.g.radio program is weekly so it does not have much sense :)
As I understand this is for one-person use so for different users I need to run 2 servers? 
And why some intresting project like this are in python? 👎 pip is horrible to update dependencies, and tbh I don't see python as a web server tool. Nodejs would have more sense to me or even Swift.

**Comment by krateng** [comment]
Python is pretty common for web technology; everyone has their personal preferences but ultimately it makes no sense to talk about that because I'm obviously not going to change it. I've also never had any reports of issues with pip dependency management, so it seems to work for this project.

> As I understand this is for one-person use so for different users I need to run 2 servers?

Correct.

> However I would like to have possibility to turn off "this week"

What do you mean exactly?

**Comment by Behinder** [comment]
I mean possibility to configure and add option to hide what is popular this
week since I scrobble once a week :)

**Comment by krateng** [comment]
Well in that case the weekly charts would simply show the charts from that day for the whole week, which is still an accurate display of your listening habits for that week. That's only one extra link that you could simply not click if you're not interested in those stats. I'm not sure I really see the issue.
