### ISSUE TITLE
Funny thing but I cannot login

### ISSUE THREAD

**Issue by Behinder** [krateng/maloja#49]
Why instead of "user" and "password" there is "password" and "response"?
I have to say such details discourage me from using such software as I don't know what "response" is.
I'll try to build my own solution, it take ages but at least it gives me peace of mind.

**Comment by krateng** [comment]
When you say you 'cannot login', do you mean you have actually tried it and it doesn't work? You just need to enter the password, this should become quickly obvious by simply entering the password. A username would be pointless since there are no users.

Please keep issues on github to the actual technical issue, if you prefer to build your own solution, you should do so.

**Comment by krateng** [comment]
I assume this has solved your issue?

**Comment by shosseinib** [comment]
Hi, I'm new here, and I have the same issue, I entered a password during the first setup in CLI, but I can log in now.

**Comment by krateng** [comment]
Try to run Maloja again with the environment variable `MALOJA_FORCE_PASSWORD=(yourpw)`, in case you simply misspelled it on first setup.
