### ISSUE TITLE
Pagination for scrobbles endpoint?

### ISSUE THREAD

**Issue by FoxxMD** [krateng/maloja#52]
I'm building a native scrobble client and want to return X number of recent scrobbles so I can verify the track hasn't already been scrobbled by another client.

I'm trying to use this url `GET myUrl/apis/mlj_1/scrobbles?max=10`, and [it looks like it should work](https://github.com/krateng/maloja/blob/master/maloja/apis/native_v1.py#L55) since `max` is in the pagination keys for `uri_to_internal`, but **all** scrobbles are returned by the response. 

Am I doing something wrong here?

Edit: Additionally, I'm having a hard time finding any documentation on how I am supposed to include my api key in the `newscrobble` request

**Comment by krateng** [comment]
The `newscrobble` request just needs the API key as a parameter `key` (either formdata or json, whatever your request type is). So e.g. `artist=Mike&title=Song&key=123456789`.

As for the `max` argument, that's a bit of a leftover from some dirty code earlier on, but I'll have a look at it and see how I could best reimplement that. However, since you're looking for scrobbles around a specific time, maybe you might simply want to give time restrictions, e.g. `myUrl/apis/mlj_1/scrobbles?since=2020/11/11&to=2020/11/13` depending on the time of the scrobble?

**Comment by FoxxMD** [comment]
Thanks for the api key help.

since/to will work for now on limiting the response but really pagination/perpage would be ideal since really I only need at most the last 10 scrobbles.

Would you prefer I close this issue since it's mostly addressed?

**Comment by krateng** [comment]
No, I'll add the limitation, that's probably a good feature to have anyway.

**Comment by krateng** [comment]
It should now work with the arguments `perpage` and `page` or simply `max`.
